"""added uuid to account

Revision ID: 0348cd54402f
Revises: aff49b4ceaff
Create Date: 2022-03-27 13:53:18.061583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0348cd54402f'
down_revision = 'aff49b4ceaff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('uuid', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_account_uuid'), 'account', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_uuid'), table_name='account')
    op.drop_column('account', 'uuid')
    # ### end Alembic commands ###
