"""bang

Revision ID: 20d742ca3ed0
Revises: 
Create Date: 2022-05-30 15:00:55.538574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20d742ca3ed0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_name'), 'profile', ['name'], unique=False)
    op.create_index(op.f('ix_profile_uuid'), 'profile', ['uuid'], unique=True)
    op.create_table('ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('month', sa.Date(), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_uuid'), 'ledger', ['uuid'], unique=True)
    op.create_table('recurring_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('recurring_dom', sa.Integer(), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurring_record_name'), 'recurring_record', ['name'], unique=False)
    op.create_index(op.f('ix_recurring_record_uuid'), 'recurring_record', ['uuid'], unique=True)
    op.create_table('record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('ledger_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ledger_id'], ['ledger.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_record_name'), 'record', ['name'], unique=False)
    op.create_index(op.f('ix_record_uuid'), 'record', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_record_uuid'), table_name='record')
    op.drop_index(op.f('ix_record_name'), table_name='record')
    op.drop_table('record')
    op.drop_index(op.f('ix_recurring_record_uuid'), table_name='recurring_record')
    op.drop_index(op.f('ix_recurring_record_name'), table_name='recurring_record')
    op.drop_table('recurring_record')
    op.drop_index(op.f('ix_ledger_uuid'), table_name='ledger')
    op.drop_table('ledger')
    op.drop_index(op.f('ix_profile_uuid'), table_name='profile')
    op.drop_index(op.f('ix_profile_name'), table_name='profile')
    op.drop_table('profile')
    # ### end Alembic commands ###
