"""added payment method to RecurringRecord

Revision ID: 33694891ec90
Revises: 48f46527f7bd
Create Date: 2022-06-15 14:12:24.880047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33694891ec90'
down_revision = '48f46527f7bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recurring_record', sa.Column('payment_method', sa.String(length=12), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recurring_record', 'payment_method')
    # ### end Alembic commands ###
