"""added uuid to items

Revision ID: 5fb5ebe68fc3
Revises: 98cf151c0197
Create Date: 2022-03-27 14:55:13.069730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fb5ebe68fc3'
down_revision = '98cf151c0197'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('uuid', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_item_uuid'), 'item', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_uuid'), table_name='item')
    op.drop_column('item', 'uuid')
    # ### end Alembic commands ###
