"""added end_month to item

Revision ID: 98cf151c0197
Revises: 0348cd54402f
Create Date: 2022-03-27 14:37:54.256461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98cf151c0197'
down_revision = '0348cd54402f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('end_month', sa.Date(), nullable=True))
    op.create_index(op.f('ix_item_end_month'), 'item', ['end_month'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_end_month'), table_name='item')
    op.drop_column('item', 'end_month')
    # ### end Alembic commands ###
