"""added name,amount,description to ledgerentry

Revision ID: ad8c11ffea7d
Revises: f408009ad25c
Create Date: 2022-03-27 15:55:37.771465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad8c11ffea7d'
down_revision = 'f408009ad25c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ledger_entry', sa.Column('name', sa.String(length=64), nullable=True))
    op.add_column('ledger_entry', sa.Column('description', sa.String(length=512), nullable=True))
    op.add_column('ledger_entry', sa.Column('amount', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_ledger_entry_name'), 'ledger_entry', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ledger_entry_name'), table_name='ledger_entry')
    op.drop_column('ledger_entry', 'amount')
    op.drop_column('ledger_entry', 'description')
    op.drop_column('ledger_entry', 'name')
    # ### end Alembic commands ###
