"""added active column to items

Revision ID: f408009ad25c
Revises: 5fb5ebe68fc3
Create Date: 2022-03-27 15:38:06.891606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f408009ad25c'
down_revision = '5fb5ebe68fc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'active')
    # ### end Alembic commands ###
